databases:
  - name: airbnbclone
    databaseName: airbnbclone
    user: airbnbclone
    region: singapore

services:
  - type: web
    name: airbnb-clone
    env: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn airbnbclone.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: airbnb-clone
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4