# Generated by Django 4.1.2 on 2022-11-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_room_category"),
        ("experiences", "0002_experience_category_alter_perk_details_and_more"),
        ("medias", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Photos",
            new_name="Photo",
        ),
    ]
